<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DaFoVectSharp" Version="2.6.2" />
      <PackageReference Include="DaFoVectSharp.ImageSharpUtils" Version="2.0.1" />
      <PackageReference Include="DaFoVectSharp.PDF" Version="3.2.1" />
      <PackageReference Include="DaFoVectSharp.Raster.ImageSharp" Version="2.1.1" />
      <PackageReference Include="DaFoVectSharp.SVG" Version="1.10.3" />
      <PackageReference Include="Magick.NET-Q8-x64" Version="14.11.1" />
      <PackageReference Include="Serilog" Version="4.3.1" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
      <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
      <PackageReference Include="SixLabors.ImageSharp.Web" Version="3.2.0" />
    </ItemGroup>

</Project>
